version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    init: true 
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    init: true
    expose:
      - "9000"
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
  
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    init: true
    expose:
      - "3306"
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yloutfi/data/mariadb
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yloutfi/data/wordpress